### ISSUE TITLE
TeamCity Plugin Version and Octopus Server Support

### ISSUE THREAD

**Issue by opnarius** [OctopusDeploy/Octopus-TeamCity#31]
Is there information on what version of TeamCityPlugin supports what version of Octopus Server?

I'm running Octopus 2019.3.3 and TeamCityPlugin 5.2.1.  Getting errors trying to push package metadata.

```text
[23:23:43]Octopus Deploy (1s)
[23:23:43]Running command:   Octo push-metadata --server http://deploy.local --apikey SECRET --package-id k8s-artifacts --version 0.0.27 --metadata-file /apps/teamcity-agent/work/f97736bd4dd4d4f1/octopus.metadata
[23:23:43]Pushing package metadata to Octopus server
[23:23:43]Octopus Deploy Command Line Tool, version 6.12.0
[23:23:43]
[23:23:44]Detected automation environment: "TeamCity/2018.1"
[23:23:44]Detected automation environment: "TeamCity/2018.1"
[23:23:44]Space name unspecified, process will run in the default space context
[23:23:44]Handshaking with Octopus Server: http://deploy.local
[23:23:44]Handshake successful. Octopus version: 2019.3.3; API version: 3.0.0
[23:23:44]Authenticated as: Teamcity (a service account)
[23:23:44]Pushing package metadata: "k8s-artifacts"...
[23:23:44]
[23:23:44]System.Exception: The document does not define a link for 'PackageMetadata'
[23:23:44]   at Octopus.Client.Model.Resource.Link(String name)
[23:23:44]   at Octopus.Client.OctopusAsyncRepository.<Link>d__178.MoveNext()
[23:23:44]--- End of stack trace from previous location where exception was thrown ---
[23:23:44]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[23:23:44]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[23:23:44]   at Octopus.Client.Repositories.Async.PackageMetadataRepository.<Push>d__4.MoveNext()
[23:23:44]--- End of stack trace from previous location where exception was thrown ---
[23:23:44]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[23:23:44]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[23:23:44]   at Octopus.Cli.Commands.Package.PushMetadataCommand.<Request>d__18.MoveNext() in C:\buildAgent\work\289bf0fca31007af\source\Octopus.Cli\Commands\Package\PushMetadataCommand.cs:line 44
[23:23:44]--- End of stack trace from previous location where exception was thrown ---
[23:23:44]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[23:23:44]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[23:23:44]   at Octopus.Cli.Commands.ApiCommand.<Execute>d__37.MoveNext() in C:\buildAgent\work\289bf0fca31007af\source\Octopus.Cli\Commands\ApiCommand.cs:line 237
[23:23:44]--- End of stack trace from previous location where exception was thrown ---
[23:23:44]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[23:23:44]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[23:23:44]   at Octopus.Cli.Commands.ApiCommand.<Execute>d__35.MoveNext() in C:\buildAgent\work\289bf0fca31007af\source\Octopus.Cli\Commands\ApiCommand.cs:line 226
[23:23:44]--- End of stack trace from previous location where exception was thrown ---
[23:23:44]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[23:23:44]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[23:23:44]   at Octopus.Cli.CliProgram.Run(String[] args) in C:\buildAgent\work\289bf0fca31007af\source\Octopus.Cli\CliProgram.cs:line 52
[23:23:44]Exit code: -3
[23:23:44]Octo.exe exit code: 253
[23:23:44]Unable to create or deploy release. Please check the build log for details on the error.
```

**Comment by matt-richardson** [comment]
The package metadata support was added in Octopus 2019.4. You'll need to upgrade your Octopus server to be able to use this build step. All other build steps will work fine.

That said, there should be a much nicer error message shown here.

**Comment by matt-richardson** [comment]
Thanks for reporting, @opnarius 
This is improved in the latest plugin - 5.2.4.

This now shows up like this:
![image](https://user-images.githubusercontent.com/373389/63063553-80ba0e80-bf40-11e9-99b8-66f016ee2643.png)
